name: 构建应用程序

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      PYTHONIOENCODING: utf-8
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller pillow

      - name: 运行构建脚本
        shell: cmd
        run: |
          chcp 65001
          python scripts/build.py
      - name: Create ZIP package
        run: |
          powershell Compress-Archive -Path dist\CursorPro.exe -DestinationPath dist\CursorPro-Windows-${{ github.ref_name }}.zip

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: CursorPro-Windows-${{ github.ref_name }}.zip
          path: dist/CursorPro-Windows-${{ github.ref_name }}.zip
          if-no-files-found: error

  build-macos:
    runs-on: macos-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller pillow

      - name: 运行构建脚本
        run: |
          python scripts/build.py

      - name: Create ZIP package
        run: |
          ditto -c -k --keepParent dist/CursorPro.app dist/CursorPro-MacOS-${{ github.ref_name }}.zip

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: CursorPro-MacOS-${{ github.ref_name }}.zip
          path: dist/CursorPro-MacOS-${{ github.ref_name }}.zip
          if-no-files-found: error

  create-release:
    needs: [build-windows, build-macos]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: 下载所有构建产物
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: 创建发布
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/CursorPro-Windows-${{ github.ref_name }}.zip/CursorPro-Windows-${{ github.ref_name }}.zip
            artifacts/CursorPro-MacOS-${{ github.ref_name }}.zip/CursorPro-MacOS-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
